name: Build Debug & Release

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Debug
        run: dotnet build --configuration Debug --no-restore -v quiet

      - name: Publish Debug
        run: dotnet publish --configuration Debug --runtime win-x64 --output ./publish/debug

      - name: Archive Debug
        run: |
          cd ./publish/debug
          7z a -tzip "../../iLearn-Debug-${{ github.sha }}.zip" *

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLearn-Debug-${{ github.sha }}
          path: iLearn-Debug-${{ github.sha }}.zip
          retention-days: 30

  build-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release
        run: dotnet build --configuration Release --no-restore -v quiet

      - name: Publish Release
        run: dotnet publish --configuration Release --runtime win-x64 --output ./publish/release

      - name: Archive Release
        run: |
          cd ./publish/release
          7z a -tzip "../../iLearn-Release-${{ github.sha }}.zip" *

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLearn-Release-${{ github.sha }}
          path: iLearn-Release-${{ github.sha }}.zip
          retention-days: 30

  build-installer:
    name: Build Installer
    runs-on: windows-latest
    needs: build-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./iLearn

      - name: Build Release Project
        run: dotnet build ./iLearn --configuration Release --no-restore -v quiet

      - name: Correct paths in Inno Setup script
        shell: pwsh
        run: |
          $issFile = "./iLearn/iLearnSetup/build.iss"
          (Get-Content $issFile -Raw) -replace 'LicenseFile=C:.*License\.rtf', 'LicenseFile=..\Assets\License.rtf' `
                                      -replace 'Source: "..\\iLearn\\bin\\', 'Source: "..\\bin\\' | Set-Content -Path $issFile

      - name: Inno Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: ./iLearn/iLearnSetup/build.iss

      - name: Archive Installer
        run: |
          cd ./iLearn/iLearnSetup/Output
          7z a -tzip "../../../iLearn-Installer-${{ github.sha }}.zip" *

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLearn-Installer-${{ github.sha }}
          path: iLearn-Installer-${{ github.sha }}.zip
          retention-days: 30
