name: Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      # --- Build & Publish Debug ---
      - name: Build Debug
        run: dotnet build --configuration Debug --no-restore

      - name: Publish Debug
        run: dotnet publish --configuration Debug --runtime win-x64 --self-contained true --output ./publish/debug

      - name: Archive Debug
        run: |
          cd ./publish/debug
          7z a -tzip "../../iLearn-Debug-${{ github.sha }}.zip" *

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLearn-Debug-${{ github.sha }}
          path: iLearn-Debug-${{ github.sha }}.zip
          retention-days: 30

      # --- Build & Publish Release ---
      - name: Build Release
        run: dotnet build --configuration Release --no-restore

      - name: Publish Release
        run: dotnet publish --configuration Release --runtime win-x64 --self-contained true --output ./publish/release

      - name: Archive Release
        run: |
          cd ./publish/release
          7z a -tzip "../../iLearn-Release-${{ github.sha }}.zip" *

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLearn-Release-${{ github.sha }}
          path: iLearn-Release-${{ github.sha }}.zip
          retention-days: 30

      # --- GitHub Release (only on tag) ---
      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            iLearn-Debug-${{ github.sha }}.zip
            iLearn-Release-${{ github.sha }}.zip
          body: |
            ## iLearn Application Release

            ### 🐞 Debug Build
            - Includes debug symbols
            - Logging enabled
            - Suitable for troubleshooting and development

            ### 🚀 Release Build
            - Optimized for performance
            - No debug symbols
            - Recommended for general users

            ### 📦 How to Use
            1. Download the appropriate zip
            2. Extract to a folder
            3. Run `iLearn.exe`

          name: "iLearn ${{ github.ref_name }}"
          tag: ${{ github.ref_name }}
          draft: false
          prerelease: false
